import { parserService } from "../backend/services/parserService";

// Define a simple interface to mock the expected output structure for type safety
interface ParsedData {
  total: number;
  basePay: number;
  bonus: number;
  penalty: number;
  // Assuming the parser also includes other necessary audit fields
}

describe("parserService - Integration Test", () => {
  it("should successfully parse sample raw text and verify numeric types", async () => {
    // Sample raw text output typically generated by an OCR service
    const raw = `
      Platform: Swiggy
      Date: 2025-10-26
      Final Total Payout: ₹420.50
      Base Trip Earnings: ₹250.00
      Incentive Bonus: ₹100.00
      Penalty Deduction: ₹50.00
    `;
    
    // Call the parser service with the raw text
    const parsed = (await parserService.parse(raw)) as ParsedData;

    // Assert that the object is defined
    expect(parsed).toBeDefined();

    // Assert that key financial fields are defined and are of type 'number'
    expect(parsed.total).toBeDefined();
    expect(typeof parsed.total === "number").toBeTruthy();
    
    expect(parsed.basePay).toBeDefined();
    expect(typeof parsed.basePay === "number").toBeTruthy();

    expect(parsed.bonus).toBeDefined();
    expect(typeof parsed.bonus === "number").toBeTruthy();

    expect(parsed.penalty).toBeDefined();
    expect(typeof parsed.penalty === "number").toBeTruthy();

    // Optional: Assert the values for deep verification
    // expect(parsed.total).toBe(420.50);
    // expect(parsed.basePay).toBe(250.00);
  });
});