import { parserService } from "../backend/services/parserService";

// Define the required structure based on backend/services/parserService.ts
interface Penalty {
  type?: string;
  amount: number;
}

interface ParsedData {
  platform?: string;
  date?: string;
  total?: number;
  basePay?: number;
  bonus?: number;
  distancePay?: number;
  penalties?: Penalty[]; // FIX: Must be an array of Penalty objects
  ratings?: { date?: string; rating?: number }[];
  rawText?: string;
}

describe("parserService - Integration Test", () => {
  it("should successfully parse sample raw text and verify numeric types", async () => {
    // Sample raw text output typically generated by an OCR service
    const raw = `
      Platform: Swiggy
      Date: 2025-10-26
      Final Total Payout: ₹420.50
      Base Trip Earnings: ₹250.00
      Incentive Bonus: ₹100.00
      Penalty Deduction: ₹50.00
    `;
    
    // Call the parser service with the raw text
    const parsed = (await parserService.parse(raw)) as ParsedData;

    // Assert that the object is defined
    expect(parsed).toBeDefined();

    // Assert that key financial fields are defined and are of type 'number'
    expect(parsed.total).toBeDefined();
    expect(typeof parsed.total === "number").toBeTruthy();
    expect(parsed.total).toBe(420.50); // Deep verification

    expect(parsed.basePay).toBeDefined();
    expect(typeof parsed.basePay === "number").toBeTruthy();
    expect(parsed.basePay).toBe(250.00);

    expect(parsed.bonus).toBeDefined();
    expect(typeof parsed.bonus === "number").toBeTruthy();
    expect(parsed.bonus).toBe(100.00);

    // FIX: Assert on the penalties array and the total amount
    expect(parsed.penalties).toBeDefined();
    expect(Array.isArray(parsed.penalties)).toBeTruthy();
    
    const totalPenalty = (parsed.penalties || []).reduce((sum, p) => sum + p.amount, 0);
    expect(totalPenalty).toBe(50.00);
  });
});